[package]
name = "rrp-client-web"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { workspace = true }
wasm-bindgen = { workspace = true }
rktk-rrp = { path = "../../lib/rktk-rrp", features = ["tsify"] }
rktk-keymanager = { path = "../../lib/rktk-keymanager", default-features = false }
web-sys = { version = "0.3.70", features = [
  "SerialPort",
  "WritableStream",
  "ReadableStream",
  "WritableStreamDefaultWriter",
  "ReadableStreamDefaultReader",
  "ReadableStreamGetReaderOptions",
  "ReadableStreamReaderMode",
  "ReadableStreamByobReader",
] }
anyhow = "1.0.86"
wasm-bindgen-futures = "0.4.43"
log = "0.4.22"
console_log = "1.0.0"
futures = { workspace = true }
serde-wasm-bindgen = "0.6.5"
tsify-next = { workspace = true }
async-lock = "3.4.0"
gloo-timers = { version = "0.3.0", features = ["futures"] }
