use crate::interface::{
    backlight::{BacklightDriver, DummyBacklightDriver},
    ble::{BleDriver, DummyBleDriver, DummyBleDriverBuilder},
    debounce::{DebounceDriver, DummyDebounceDriver},
    display::{DisplayDriver, DummyDisplayDriver, DummyDisplayDriverBuilder},
    double_tap::{DoubleTapResetDriver, DummyDoubleTapResetDriver},
    encoder::{DummyEncoderDriver, EncoderDriver},
    keyscan::KeyscanDriver,
    mouse::{DummyMouseDriver, DummyMouseDriverBuilder, MouseDriver},
    split::{DummySplitDriver, SplitDriver},
    storage::{DummyStorageDriver, StorageDriver},
    usb::{DummyUsbDriver, DummyUsbDriverBuilder, UsbDriver},
    DriverBuilder, DriverBuilderWithTask,
};

#[derive(bon::Builder)]
pub struct Drivers<
    KeyScan: KeyscanDriver,
    Split: SplitDriver = DummySplitDriver,
    Debounce: DebounceDriver = DummyDebounceDriver,
    Ble: BleDriver = DummyBleDriver,
    Usb: UsbDriver = DummyUsbDriver,
    Backlight: BacklightDriver = DummyBacklightDriver,
    Storage: StorageDriver = DummyStorageDriver,
    Mouse: MouseDriver = DummyMouseDriver,
    Display: DisplayDriver = DummyDisplayDriver,
    MouseBuilder: DriverBuilder<Output = Mouse> = DummyMouseDriverBuilder,
    DisplayBuilder: DriverBuilder<Output = Display> = DummyDisplayDriverBuilder,
    UsbBuilder: DriverBuilderWithTask<Driver = Usb> = DummyUsbDriverBuilder,
    BleBuilder: DriverBuilderWithTask<Driver = Ble> = DummyBleDriverBuilder,
    DoubleTapReset: DoubleTapResetDriver = DummyDoubleTapResetDriver,
    Encoder: EncoderDriver = DummyEncoderDriver,
> {
    pub(super) double_tap_reset: Option<DoubleTapReset>,
    pub(super) keyscan: KeyScan,
    pub(super) debounce: Option<Debounce>,
    pub(super) encoder: Option<Encoder>,
    pub(super) split: Option<Split>,
    pub(super) backlight: Option<Backlight>,
    pub(super) storage: Option<Storage>,

    pub(super) ble_builder: Option<BleBuilder>,
    pub(super) usb_builder: Option<UsbBuilder>,
    pub(super) mouse_builder: Option<MouseBuilder>,
    pub(super) display_builder: Option<DisplayBuilder>,
}
