# This config is used by internal `cargo xtask` command.
# For more detail, see `tools/xtask`

check_skip_global = ["_check", "default"]
check_env = { DEFMT_LOG = "trace" }
test_features_global = ["_check"]
doc_features_global = ["_check"]

# =========== Core crates ============

[crates.rktk]
check_group_features = [["defmt", "log"]]

[crates.rktk-rrp]
check_at_least_one_of = [["server", "client"]]
test_enabled = true

[crates.rktk-keymanager]
check_group_features = [["serde", "postcard"]]
test_enabled = true

# =========== Drivers ==========

[crates.rktk-drivers-nrf]
check_features = ["_nrfxx", "nightly", "power"]
check_group_features = [["softdevice", "softdevice-ble"], ["defmt", "log"]]
check_mutually_exclusive_features = [
  [
    "softdevice-ble",
    "esb",
  ],
  [
    "esb",
    "sdc",
  ],
  [
    "softdevice-ble",
    "sdc",
  ],
]

[crates.rktk-drivers-rp]
check_features = ["_check"]
check_skip = []

[crates.rktk-drivers-common]
check_group_features = [
  [
    "defmt",
    "defmt-timestamp",
    "defmt-usb",
  ],
  [
    "trouble",
    "reporter-trouble",
  ],
]
test_enabled = true
test_features = []


# ========== Tools ==========

[crates.rktk-client]
check_at_least_one_of = [["web", "native"]]
check_mutually_exclusive_features = [["web", "native"]]
doc_disabled = true

[crates.xtask]
doc_disabled = true
check_no_powerset = true

# ========== Keyboards ==========

[crates.example-corne]
check_no_powerset = true
doc_disabled = true

[crates.example-corne-nrf]
check_no_powerset = true
doc_disabled = true

[crates.example-dummy-kb-rp]
doc_disabled = true
check_no_powerset = true

[crates.neg-nrf]
check_features = ["left", "alloc", "paw3395", "log", "defmt"]
check_at_least_one_of = [["sd", "trouble", "cs-impl"]]
check_mutually_exclusive_features = [["sd", "trouble", "cs-impl"]]
check_skip = ["_check", "default", "right", "pmw3360"]
check_build = true
