[config]
default_to_workspace = false
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.run-usb]
script = 'cd keyboards/keyball61-nrf52840 && cargo make run-usb'

[tasks.run-ble]
script = 'cd keyboards/keyball61-nrf52840 && cargo make run-ble'

[tasks.run-rrp]
script = 'cd rrp-web && pnpm dev'

[tasks.run-rp]
script = 'cd keyboards/keyball61-rp2040 && cargo make run-rp'

[tasks.check-all]
script = '''
#!@duckscript
pwd = pwd
handle = gitignore_path_array ./
for path in ${handle}
  if ends_with ${path} Cargo.toml
    if not eq ${path} ./Cargo.toml
      dir = dirname ${path}
      cd ${dir}
      exec --fail-on-error cargo clippy
      cd ${pwd}
    end
  end
end
'''

[tasks.test-all]
script = '''
#!@duckscript
fn test
  pwd = pwd
  cd ${1}
  exec --fail-on-error cargo test
  cd ${pwd}
end

test ./lib/rktk-keymanager
'''

[tasks.ra-check]
script = '''
#!@duckscript
path = set ${1}

:start

path = dirname ${path}
if not ${path}
  goto :end
end

existing = is_path_exists ${path}/Cargo.toml

if ${existing}
  goto :end
else
  goto :start
end

:end

cd ${path}
exec cargo clippy --message-format=json
'''
