[config]
default_to_workspace = false
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.run-usb]
script = 'cd keyboards/keyball61-nrf52840 && cargo make run-usb'

[tasks.run-ble]
script = 'cd keyboards/keyball61-nrf52840 && cargo make run-ble'

[tasks.run-rrp]
script = 'cd rrp-desktop && pnpm tauri dev'

[tasks.check-all]
script = '''
#!@duckscript
pwd = pwd
handle = gitignore_path_array ./
for path in ${handle}
  if ends_with ${path} Cargo.toml
    if not eq ${path} ./Cargo.toml
      dir = dirname ${path}
      cd ${dir}
      exec --fail-on-error cargo clippy
      cd ${pwd}
    end
  end
end
'''

[tasks.test-all]
script = '''
#!@duckscript
fn test
  pwd = pwd
  cd ${1}
  exec --fail-on-error cargo test
  cd ${pwd}
end

test ./lib/rktk-keymanager
'''

[tasks.ra-check]
script = '''
#!@duckscript
if starts_with ${2} rrp-desktop
  cd rrp-desktop/src-tauri
  exec cargo clippy --message-format=json
elseif starts_with ${2} rktk
  cd lib/${2}
  exec cargo clippy --message-format=json
else
  cd keyboards/${2}
  exec cargo clippy --message-format=json
end
'''
