cargo-features = ["per-package-target"]

[package]
name = "neg-rp"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
# tombi: lint.rules.key-not-allowed.disabled = true
forced-target = "thumbv6m-none-eabi"

[lib]
bench = false
doctest = false
path = "src/lib.rs"
test = false

[[bin]]
bench = false
doctest = false
name = "neg_rp_master"
test = false

[[bin]]
name = "neg_rp_slave"
test = false
doctest = false
bench = false

[dependencies]
cfg-if = { workspace = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-embedded-hal = { workspace = true }
embassy-executor = { workspace = true, features = [
  "platform-cortex-m",
  "executor-interrupt",
  "executor-thread",
] }
embassy-rp = { workspace = true, features = [
  "critical-section-impl",
  "rp2040",
  "time-driver",
] }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
# alloc
embedded-alloc = { workspace = true, optional = true }
log = { workspace = true, optional = true }
neg-common = { path = "../neg-common/" }
portable-atomic = { workspace = true, features = ["unsafe-assume-single-core"] }
rktk = { workspace = true }
rktk-drivers-common = { workspace = true }
rktk-drivers-rp = { workspace = true }
rktk-log = { workspace = true }

[features]
default = ["rrp"]
_check = ["left", "log", "pmw3360"]
alloc = ["dep:embedded-alloc", "rktk/alloc"]
defmt = [
  "dep:defmt",
  "rktk-drivers-common/defmt-timestamp",
  "rktk-drivers-common/defmt-usb",
  "rktk-drivers-rp/defmt",
  "rktk-log/defmt",
  "rktk/defmt",
]
left = ["neg-common/left"]
log = [
  "dep:log",
  "rktk-drivers-common/log",
  "rktk-drivers-rp/log",
  "rktk-log/log",
  "rktk/log",
]
paw3395 = ["neg-common/paw3395"]
pmw3360 = []
right = ["neg-common/right"]
rrp = ["rktk/rrp"]
