import { Key, Media, Special } from "rktk-rrp-client-webhid";

export const MODIFIER_KEYS: Map<number, string> = new Map([
  [0x01, "Ctrl(L)"],
  [0x02, "Shft(L)"],
  [0x04, "Alt(L)"],
  [0x08, "Gui(L)"],
  [0x10, "Ctrl(R)"],
  [0x20, "Shft(R)"],
  [0x40, "Alt(R)"],
  [0x80, "Gui(R)"],
]);

export const MOUSE_KEYS: Map<number, string> = new Map([
  [0x01, "Left"],
  [0x02, "Right"],
  [0x04, "Middle"],
  [0x08, "Back"],
  [0x10, "Forward"],
]);

export const SPECIAL_KEYS: Map<Special, string> = new Map(
  [
    ["MoScrl", "Scroll Mode"],
    ["FlashClear", "Clear Flash"],
    ["OutputBle", "Output BLE"],
    ["OutputUsb", "Output USB"],
    ["BleBondClear", "Clear BLE Bond"],
    ["Bootloader", "Bootloader"],
  ] as const,
);

export const LAYER_KEYS: Map<string, string> = new Map([
  ["Toggle", "Toggle"],
  ["Momentary", "Momentary"],
]);

export const MEDIA_KEYS: Map<Media, string> = new Map([
  ["Zero", "Zero"],
  ["Play", "Play"],
  ["Pause", "Pause"],
  ["Record", "Record"],
  ["NextTrack", "NextTrack"],
  ["PrevTrack", "PrevTrack"],
  ["Stop", "Stop"],
  ["RandomPlay", "RandomPlay"],
  ["Repeat", "Repeat"],
  ["PlayPause", "PlayPause"],
  ["Mute", "Mute"],
  ["VolumeIncrement", "VolUp"],
  ["VolumeDecrement", "VolDn"],
  ["Reserved", "Reserved"],
]);

export const NORMAL_KEYS: Map<Key, string> = new Map([
  ["A", "A"],
  ["B", "B"],
  ["C", "C"],
  ["D", "D"],
  ["E", "E"],
  ["F", "F"],
  ["G", "G"],
  ["H", "H"],
  ["I", "I"],
  ["J", "J"],
  ["K", "K"],
  ["L", "L"],
  ["M", "M"],
  ["N", "N"],
  ["O", "O"],
  ["P", "P"],
  ["Q", "Q"],
  ["R", "R"],
  ["S", "S"],
  ["T", "T"],
  ["U", "U"],
  ["V", "V"],
  ["W", "W"],
  ["X", "X"],
  ["Y", "Y"],
  ["Z", "Z"],
  ["D1", "1"],
  ["D2", "2"],
  ["D3", "3"],
  ["D4", "4"],
  ["D5", "5"],
  ["D6", "6"],
  ["D7", "7"],
  ["D8", "8"],
  ["D9", "9"],
  ["D0", "0"],
  ["Enter", "Enter"],
  ["Escape", "ESC"],
  ["Backspace", "BS"],
  ["Tab", "Tab"],
  ["Space", "Space"],
  ["Minus", "-"],
  ["Equal", "="],
  ["LeftBracket", "["],
  ["RightBracket", "]"],
  ["Backslash", "\\"],
  ["NonUsHash", "NonUsHash"],
  ["Semicolon", ";"],
  ["Quote", "'"],
  ["Grave", "`"],
  ["Comma", ","],
  ["Dot", "."],
  ["Slash", "/"],
  ["CapsLock", "CapsLock"],
  ["F1", "F1"],
  ["F2", "F2"],
  ["F3", "F3"],
  ["F4", "F4"],
  ["F5", "F5"],
  ["F6", "F6"],
  ["F7", "F7"],
  ["F8", "F8"],
  ["F9", "F9"],
  ["F10", "F10"],
  ["F11", "F11"],
  ["F12", "F12"],
  ["PrintScreen", "PrtSc"],
  ["ScrollLock", "ScrollLock"],
  ["Pause", "Pause"],
  ["Insert", "Insert"],
  ["Home", "Home"],
  ["PageUp", "PgUp"],
  ["Delete", "Delete"],
  ["End", "End"],
  ["PageDown", "PgDn"],
  ["Right", "→"],
  ["Left", "←"],
  ["Down", "↓"],
  ["Up", "↑"],
  ["NumLock", "NumLock"],
  ["KpSlash", "KpSlash"],
  ["KpAsterisk", "KpAsterisk"],
  ["KpMinus", "KpMinus"],
  ["KpPlus", "KpPlus"],
  ["KpEnter", "KpEnter"],
  ["Kp1", "Kp1"],
  ["Kp2", "Kp2"],
  ["Kp3", "Kp3"],
  ["Kp4", "Kp4"],
  ["Kp5", "Kp5"],
  ["Kp6", "Kp6"],
  ["Kp7", "Kp7"],
  ["Kp8", "Kp8"],
  ["Kp9", "Kp9"],
  ["Kp0", "Kp0"],
  ["KpDot", "KpDot"],
  ["NonUsBackslash", "NonUsBackslash"],
  ["Application", "Application"],
  ["KbPower", "KbPower"],
  ["KpEqual", "KpEqual"],
  ["F13", "F13"],
  ["F14", "F14"],
  ["F15", "F15"],
  ["F16", "F16"],
  ["F17", "F17"],
  ["F18", "F18"],
  ["F19", "F19"],
  ["F20", "F20"],
  ["F21", "F21"],
  ["F22", "F22"],
  ["F23", "F23"],
  ["F24", "F24"],
  ["Execute", "Execute"],
  ["Help", "Help"],
  ["Menu", "Menu"],
  ["Select", "Select"],
  ["Stop", "Stop"],
  ["Again", "Again"],
  ["Undo", "Undo"],
  ["Cut", "Cut"],
  ["Copy", "Copy"],
  ["Paste", "Paste"],
  ["Find", "Find"],
  ["Mute", "Mute"],
  ["VolumeUp", "VolumeUp"],
  ["VolumeDown", "VolumeDown"],
  ["LockingCapsLock", "LockingCapsLock"],
  ["LockingNumLock", "LockingNumLock"],
  ["LockingScrollLock", "LockingScrollLock"],
  ["KpComma", "KpComma"],
  ["KpEqualSign", "KpEqualSign"],
  ["International1", "Int1"],
  ["International2", "Int2"],
  ["International3", "Int3"],
  ["International4", "Int4"],
  ["International5", "Int5"],
  ["International6", "Int6"],
  ["International7", "Int7"],
  ["International8", "Int8"],
  ["International9", "Int9"],
  ["Lang1", "Lang1"],
  ["Lang2", "Lang2"],
  ["Lang3", "Lang3"],
  ["Lang4", "Lang4"],
  ["Lang5", "Lang5"],
  ["Lang6", "Lang6"],
  ["Lang7", "Lang7"],
  ["Lang8", "Lang8"],
  ["Lang9", "Lang9"],
  ["AltErase", "AltErase"],
  ["SysReq", "SysReq"],
  ["Cancel", "Cancel"],
  ["Clear", "Clear"],
  ["Prior", "Prior"],
  ["Return", "Return"],
  ["Separator", "Separator"],
  ["Out", "Out"],
  ["Oper", "Oper"],
  ["ClearAgain", "ClearAgain"],
  ["CrSel", "CrSel"],
  ["ExSel", "ExSel"],
  ["Kp00", "Kp00"],
  ["Kp000", "Kp000"],
  ["ThousandsSeparator", "ThousandsSeparator"],
  ["DecimalSeparator", "DecimalSeparator"],
  ["CurrencyUnit", "CurrencyUnit"],
  ["CurrencySubUnit", "CurrencySubUnit"],
  ["KpLeftParen", "KpLeftParen"],
  ["KpRightParen", "KpRightParen"],
  ["KpLeftBrace", "KpLeftBrace"],
  ["KpRightBrace", "KpRightBrace"],
  ["KpTab", "KpTab"],
  ["KpBackspace", "KpBackspace"],
  ["KpA", "KpA"],
  ["KpB", "KpB"],
  ["KpC", "KpC"],
  ["KpD", "KpD"],
  ["KpE", "KpE"],
  ["KpF", "KpF"],
  ["KpXor", "KpXor"],
  ["KpPower", "KpPower"],
  ["KpPercent", "KpPercent"],
  ["KpLess", "KpLess"],
  ["KpGreater", "KpGreater"],
  ["KpAmpersand", "KpAmpersand"],
  ["KpDblAmpersand", "KpDblAmpersand"],
  ["KpVerticalBar", "KpVerticalBar"],
  ["KpDblVerticalBar", "KpDblVerticalBar"],
  ["KpColon", "KpColon"],
  ["KpHash", "KpHash"],
  ["KpSpace", "KpSpace"],
  ["KpAt", "KpAt"],
  ["KpExclam", "KpExclam"],
  ["KpMemStore", "KpMemStore"],
  ["KpMemRecall", "KpMemRecall"],
  ["KpMemClear", "KpMemClear"],
  ["KpMemAdd", "KpMemAdd"],
  ["KpMemSubtract", "KpMemSubtract"],
  ["KpMemMultiply", "KpMemMultiply"],
  ["KpMemDivide", "KpMemDivide"],
  ["KpPlusMinus", "KpPlusMinus"],
  ["KpClear", "KpClear"],
  ["KpClearEntry", "KpClearEntry"],
  ["KpBinary", "KpBinary"],
  ["KpOctal", "KpOctal"],
  ["KpDecimal", "KpDecimal"],
  ["KpHexadecimal", "KpHexadecimal"],
]);
