[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"
RKTK_CONFIG_PATH = { value = "../rktk.json", relative = true }
