[package]
name = "rrp-desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rrp_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-shell = "2.0.0-rc"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
specta = { workspace = true }
tauri-specta = { version = "2.0.0-rc.17", features = ["derive", "typescript"] }
specta-typescript = "0.0.7"

tokio-serial = { version = "5.4.4" }
serialport = { version = "4.5.0", features = [
  "serde",
], default-features = false }
tokio = { version = "1.39.2", features = ["full"] }
anyhow = "1.0.86"
futures = { workspace = true }

rktk-rrp = { path = "../../lib/rktk-rrp", features = ["specta"] }
rktk-keymanager = { path = "../../lib/rktk-keymanager", default-features = false }
