[package]
name = "rktk-client"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rktk = { workspace = true }
ssmarshal = { workspace = true, features = ["std"] }
rktk-rrp = { workspace = true, features = ["client"] }
rktk-keymanager = { workspace = true }

dioxus = { version = "0.6.0", features = [] }

serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true, features = ["async-await"] }
strum = { workspace = true }
jiff = "0.2.1"

log = { workspace = true }
tracing-log = { version = "0.2.0", features = ["log-tracer"] }

kle-serial = { version = "0.3.1" }

# web deps
web-sys = { workspace = true, optional = true, features = [
  "Navigator",
  "Window",
  "ResizeObserver",
  "Hid",
  "HidCollectionInfo",
  "HidConnectionEvent",
  "HidConnectionEventInit",
  "HidDevice",
  "HidDeviceFilter",
  "HidDeviceRequestOptions",
  "HidInputReportEvent",
  "HidInputReportEventInit",
  "HidReportInfo",
  "HidReportItem",
  "HiddenPluginEventInit",
  "HidUnitSystem",
] }
js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
serde-wasm-bindgen = { version = "0.6.5", optional = true }

# native deps
smol = { version = "2.0.2", optional = true }
async-hid = { version = "0.4.0", optional = true }
async-channel = "2.3.1"

[features]
_check = ["web"]

web = [
  "dioxus/web",
  "dep:web-sys",
  "dep:js-sys",
  "dep:wasm-bindgen-futures",
  "dep:serde-wasm-bindgen",
  "dep:wasm-bindgen",
  "jiff/js",
]
native = ["dioxus/desktop", "dep:smol", "dep:async-hid"]
