cargo-features = ["per-package-target"]

[package]
name = "keyball61-nrf"
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
forced-target = "thumbv7em-none-eabihf"

[lib]
path = "src/lib.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "keyball61"
test = false
doctest = false
bench = false

[dependencies]
keyball61-common = { path = "../keyball61-common/" }

rktk = { workspace = true }
rktk-drivers-nrf = { workspace = true, features = ["nightly"] }
rktk-drivers-common = { workspace = true }

embassy-executor = { workspace = true, features = [
  "arch-cortex-m",
  "executor-thread",
  "executor-interrupt",
  "nightly",
] }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
embassy-embedded-hal = { workspace = true }

embassy-nrf = { workspace = true, features = [
  "gpiote",
  "time-driver-rtc1",
  "nrf52840",
  "nfc-pins-as-gpio",
  "unstable-pac",
] }
nrf-softdevice = { workspace = true, features = [
  "ble-peripheral",
  "ble-central",
  "critical-section-impl",
  "s140",
  "nrf52840",
] }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }

once_cell = { workspace = true, features = ["critical-section"] }

[features]
_check = []

usb = ["rktk-drivers-nrf/softdevice"]
ble = ["rktk-drivers-nrf/softdevice-ble"]
default = ["ble", "usb"]
