[package]
name = "ra-check"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
duct = { workspace = true }
anyhow = { workspace = true }

[features]
_check = []
