[package]
name = "xtask"
description = "Internal xtask command for rktk"
publish = false
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
anyhow = { workspace = true }
duct = "1.0.0"
colored = "3.0.0"
cargo_metadata = "0.19.0"
toml = "0.8.19"
serde = { workspace = true }
serde_json = { workspace = true }
dircpy = { version = "0.3.19", default-features = false }
sha2 = "0.10.8"
hex = "0.4.3"

[features]
_check = []
