[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.build-min-size]
script = '''
cargo build -Z build-std=core,panic_abort -Z build-std-features=panic_immediate_abort --profile size-opt
'''

[tasks.run-rp]
script = '''
#!@duckscript
success = set false
r = range 1 30
for i in ${r}
  if not ${success}
    code = exec --get-exit-code cargo run -Z build-std=core,panic_abort -Z build-std-features=panic_immediate_abort --profile size-opt
    success = eq ${code} 0
  end
  if not ${success}
    sleep 750
  end
end
'''
