# Configuration to minimize binary size

[profile.release]
debug = true
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
rustflags = ["-Zlocation-detail=none"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = [
  # Temporary disabled (ref: #62)
  # "panic_immediate_abort", 
  "optimize_for_size",
]
