[package]
name = "keyball-common"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rktk-drivers-common = { workspace = true }
rktk = { workspace = true }
