[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs -d"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
RKTK_COL_PIN_COUNT = "4"
RKTK_ROW_PIN_COUNT = "5"
RKTK_COLS = "7"
RKTK_ROWS = "5"
RKTK_LAYER_COUNT = "5"
RKTK_RIGHT_LED_COUNT = "34"
RKTK_LEFT_LED_COUNT = "37"
RKTK_CONFIG_PATH = { value = "rktk.toml", relative = true }

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
