name: doc

on:
  push:
    branches: ["master"]
    paths:
      - '.github/workflows/doc.yml'
      - '.github/workflows/setup-rust/action.yaml'
      - '**.toml'
      - '**.rs'
      - '**.lock'
      - '**.md'

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup rust
      uses: ./.github/workflows/setup-rust
      with:
        target: "thumbv6m-none-eabi,thumbv7em-none-eabihf"

    - uses: r7kamura/rust-problem-matchers@v1

    - name: Generate docs
      run: cargo rktk internal doc

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc.merged/

  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: check-and-doc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
