name: Build and deploy rktk rust api docs

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/doc.yml"
      - ".github/workflows/setup-rust/action.yaml"
      - "crates/rktk/wrangler.jsonc"
      - "**.toml"
      - "**.rs"
      - "**.lock"
      - "**.md"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: ./.github/workflows/setup-rust
        with:
          target: "thumbv6m-none-eabi,thumbv7em-none-eabihf"

      - uses: r7kamura/rust-problem-matchers@v1

      - name: Build docs
        run: cargo xtask doc

      - name: Setup pnpm
        uses: ./.github/workflows/setup-pnpm

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --assets ./target/doc.merged/ --name rktk-rust-docs --compatibility-date 2025-06-07
