name: Rust check

on:
  push:
    paths:
      - '.github/workflows/lib-check.yml'
      - '**.rs'
      - '**.toml'
      - '**.lock'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lib-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: "nightly-2024-08-01"
        components: "clippy,rust-src"
        target: "thumbv6m-none-eabi,thumbv7em-none-eabihf"
        rustflags: ""

    - name: Install cargo deps
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-make,wasm-pack

    - name: Run rust check
      run: cargo make check-all

    - name: Run rust test
      run: cargo make test-all

    - name: Build rust library for rrp-web
      run: cd rrp-web/rrp-client-web && wasm-pack build --release

    - name: Upload rrp-web-client package
      uses: actions/upload-artifact@v4
      with:
        name: rrp-client-web
        path: rrp-web/rrp-client-web/pkg
