name: lib

on:
  push:
    branches: ["master"]
    paths:
      - '.github/workflows/lib.yml'
      - '.github/workflows/setup-rust/action.yaml'
      - '**.toml'
      - '**.rs'
      - '**.lock'
  pull_request:
    paths:
      - '.github/workflows/lib.yml'
      - '.github/workflows/setup-rust/action.yaml'
      - '**.toml'
      - '**.rs'
      - '**.lock'

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1

jobs:
  check-and-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup rust
      uses: ./.github/workflows/setup-rust
      with:
        components: "clippy,rust-src"
        target: "thumbv6m-none-eabi,thumbv7em-none-eabihf"

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - uses: r7kamura/rust-problem-matchers@v1

    - name: Run rust check
      run: cargo rktk internal check all

    - name: Generate docs
      run: cargo rktk internal doc

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc.merged/

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup rust
      uses: ./.github/workflows/setup-rust
      with:
        components: "rust-src"
        target: ""

    - uses: r7kamura/rust-problem-matchers@v1

    - name: Run rust test
      run: cargo rktk internal test all

  doc-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: check-and-doc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
