name: lib

on:
  push:
    branches: ["master"]
    paths:
      - '.github/workflows/lib.yml'
      - '.github/workflows/setup-rust/action.yaml'
      - '**.toml'
      - '**.rs'
      - '**.lock'
  pull_request:
    paths:
      - '.github/workflows/lib.yml'
      - '.github/workflows/setup-rust/action.yaml'
      - '**.toml'
      - '**.rs'
      - '**.lock'

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1

jobs:
  check-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup rust
      uses: ./.github/workflows/setup-rust
      with:
        components: "clippy,rust-src"
        target: "thumbv6m-none-eabi,thumbv7em-none-eabihf"

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - uses: r7kamura/rust-problem-matchers@v1

    - name: Run rust check
      run: cargo rktk internal check all

    - name: Run rust test
      run: cargo rktk internal test all
