name: Run rust check and test

on:
  push:
    branches: ["master"]
    paths: &paths
      - ".github/workflows/lib.yml"
      - ".github/workflows/setup-rust/action.yaml"
      - "**.toml"
      - "**.rs"
      - "**.lock"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths: *paths
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1

jobs:
  rust-check-and-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: ./.github/workflows/setup-rust
        with:
          components: "clippy,rust-src"
          target: "thumbv6m-none-eabi,thumbv7em-none-eabihf"

      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
          version: 1.0

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack,cargo-llvm-lines,uf2deploy

      - uses: r7kamura/rust-problem-matchers@v1

      - name: Run rust check
        run: cargo xtask check all

      - name: Run rust test
        run: cargo xtask test all

      - name: Post binary stats as PR comment
        if: github.event_name == 'pull_request'
        run: |
          cargo xtask stats neg-nrf --features right,trouble,pmw3360 --bin neg_nrf_master --gh-output
          gh pr comment "$PR_NUMBER" --body-file /tmp/stats-comment.md --delete-last --yes
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
