name: Build and deploy rktk-client

on:
  push:
    branches: ["master"]
    paths:
      - "crates/rktk-client/**"
      - "crates/rktk-keymanager/**.rs"
      - "crates/rktk-rrp/**.rs"
      - ".github/workflows/rktk-client.yml"
      - ".github/workflows/setup-rust/action.yaml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-deploy-rktk-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: ./.github/workflows/setup-rust
        with:
          components: "rust-src"
          target: "wasm32-unknown-unknown"

      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack,dioxus-cli@0.7.0-rc.1

      - name: Setup pnpm
        uses: ./.github/workflows/setup-pnpm

      - name: Build
        run: cd crates/rktk-client && pnpm build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --assets ./target/dx/rktk-client/release/web/public --name rktk-client --compatibility-date 2025-06-07
