name: rrp-web check

on:
  push:
    paths:
      - '.github/workflows/rrp-web-check.yml'
      - 'rrp-web/**'
  pull_request:

env:
  CARGO_TERM_COLOR: always
jobs:
  rrp-web:
    runs-on: ubuntu-latest
    needs: lib-check
    steps:
    - name: Download rrp-client-web packages
      uses: actions/download-artifact@v4
      with:
        name: rrp-client-web
        path: rrp-web/rrp-client-web/pkg

    - uses: pnpm/action-setup@v4
      name: Setup pnpm
      with:
        version: 9
        run_install: false
        cwd: rrp-web

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: rrp-web/pnpm-lock.yaml

    - name: pnpm install
      run: cd rrp-web && pnpm install

    - name: Type check rrp-web
      run: cd rrp-web && pnpm tsc --noEmit
